cursor #f9ddd4
cursor_text_color #dcc1b8

foreground            #f9ddd4
background            #1e100b
selection_foreground  #49290e
selection_background  #f1bc96
url_color             #ffb59c

color0   #1e100b
color1   #ff7672
color2   #98ff7f
color3   #ffe572
color4   #f29d81
color5   #763721
color6   #ffb59c
color7   #fff3ef
color8   #47413f
color9   #ffa29f
color10  #b6ffa5
color11  #ffeea5
color12  #ffc0aa
color13  #ffcbb9
color14  #ffddd2
color15  #fffaf8
