# Font Configuration
font_size 10.5
font_family FiraCode Nerd Font Mono

# Cursor Configuration
cursor_shape beam
shell_integration enabled

# Window Config
window_padding_width 12
background_opacity 0.95
background_blur 12

# Scrollback
scrollback_lines 8000

# Terminal features
strip_trailing_spaces smart
notify_on_cmd_finish invisible
enable_audio_bell no

# Keybinds
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0
map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard

mouse_map left click ungrabbed mouse_handle_click selection link prompt

# Tab configuration
tab_bar_style powerline
tab_bar_align left

# Dank color generation
include dank-tabs.conf
include dank-theme.conf
