# https://github.com/DreamMaoMao/mango/wiki/

source=~/.config/mango/animations.conf
source=~/.config/mango/binds.conf
source=~/.config/mango/env.conf
source=~/.config/mango/execs.conf
source=~/.config/mango/general.conf
source=~/.config/mango/io.conf
source=~/.config/mango/layouts.conf
source=~/.config/mango/rules.conf

source=~/.config/mango/dms/colors.conf

