exec-once=xremap --watch=config,device /home/lufimio/.config/xremap/config.yml
exec-once=clipse -listen
exec-once=wayscriber --daemon
exec-once=vicinae server
exec-once=mpd
exec-once=espanso start
exec-once=easyeffects --gapplication-service
exec-once=dbus-update-activation-environment --systemd DISPLAY XAUTHORITY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
