# Misc - System
xwayland_persistence=1
syncobj_enable=0
allow_lock_transparent=1
allow_shortcuts_inhibit=1

# Misc - Focus
focus_on_activate=1
sloppyfocus=1
warpcursor=1
focus_cross_monitor=1
exchange_cross_monitor=1
focus_cross_tag=1
focus_on_activate=1
scratchpad_cross_monitor=1
single_scratchpad=1

# Misc - Floating
enable_floating_snap=1

# Theming - Dimentions
borderpx=2
gappih=6
gappiv=6
gappoh=18
gappov=9

# Theming - Cursor
cursor_size=24
cursor_theme=Adwaita

# Window Effects
blur=1
blur_layer=1
blur_optimized=1
blur_params_radius=5
blur_params_num_passes=2
blur_params_noise=0.02

shadows=1
layer_shadows=1
shadow_only_floating=1
shadows_size=5
shadows_blur=10
shadows_position_y=3
shadowscolor=0x1a1a1aee

border_radius=15
focused_opacity=1.0
unfocused_opacity=0.6


# Overview Setting
hotarea_size=10
enable_hotarea=1
ov_tab_mode=0
overviewgappi=5
overviewgappo=30
