#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title OCR Last Screenshot
# @vicinae.mode compact
# @vicinae.exec ["/bin/bash"]

file=$(find /home/lufimio/Pictures/Screenshots/ -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
tesseract "$file" - | wl-copy
echo "Ran OCR on $(basename "$file")"
