#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Set AAC Codec for WH-CH720N
# @vicinae.mode compact
# @vicinae.exec ["/bin/bash"]

pactl set-card-profile bluez_card.40_72_18_BA_E8_C9 a2dp-sink
pactl set-default-source alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
echo "Done"
