virtual_modifiers:
  - CapsLock

modmap:
  - name: CapsLock to Esc
    remap:
      CapsLock:
        alone: Esc
        held: CapsLock

keymap:
  - name: Fn Keys
    remap:
      F6: Mute
      F7: VolumeDown
      F8: VolumeUp
      Mute: F6
      VolumeDown: F7
      VolumeUp: F8

  - name: CapsLock + HJKL → Arrow Keys
    remap:
      CapsLock-h: Left
      CapsLock-j: Down
      CapsLock-k: Up
      CapsLock-l: Right

  - name: CapsLock + Left/Right → Home/End
    remap:
      CapsLock-Left: Home
      CapsLock-Right: End
