# Bar
exec-once = waybar -c /home/lufimio/.config/waybar/config-hyprland.jsonc
# exec-once = ~/.config/hypr/hypr/scripts/waybar-launcher
# Wallpaper
exec-once = swww-daemon --format xrgb
exec-once = waypaper --restore
# Volume/Brightness GUI
exec-once = swayosd-server
# Keyboard Modification
exec-once = xremap ~/.config/xremap/config.yml --watch
# Clipboard
exec-once = clipse -listen
# Application Launcher Daemon
exec-once = vicinae server
# Idle Daemon
exec-once = hypridle
# Plugins
exec-once = hyprpm reload -nn
# Notification Daemon
exec-once = swaync
# Window Switcher
exec-once = hyprswitch init --size-factor 4
# Authentication Agent
exec-once = systemctl --user start hyprpolkitagent
# dbus enviornment vars and stuff
exec-once = dbus-update-activation-environment --systemd DISPLAY XAUTHORITY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP 
# gnome keyring unlock
exec-once = gnome-keyring-daemon --start --components=secrets


# Cloudflare Because Internet Blockage Issues
# exec-once = warp-cli connect

exec-once = [ workspace special:music silent ] kitty rmpc
exec-once = [ workspace special:discord silent ] discord
